apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: react
  labels:
    app: react
spec:
  selector:
    matchLabels:
      app: react
      tier: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: react
        tier: frontend
    spec:
      containers:
      - image: https://index.docker.io/v1/react-app:latest
        name: react
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 443
          name: https
      imagePullSecrets:
      - name: regcred